const db = require("../config/connection");
const { User, Product, Category, Order } = require("../models");

db.once("open", async () => {
  await Category.deleteMany();

  const categories = await Category.insertMany([
    { name: "vegetables" },
    { name: "fruits" },
    { name: "herbs" },
  ]);

  console.log("categories seeded");

  await User.deleteMany();



  const user = await User.insertMany([
    {
    firstName: "Peter",
    lastName: "Griffin",
    gardenAddress: "Seattle",
    email: "peter@test.com",
    password: "password",
    orders: [
      {
        // products: [products[0]._id, products[0]._id, products[1]._id],
      },
    ],
  },
  {
    firstName: "Chris",
    lastName: "Griffin",
    gardenAddress: "Seattle1",
    email: "chris@test.com",
    password: "password",
    orders: [
      {
        // products: [products[0]._id, products[0]._id, products[1]._id],
      },
    ],
  },
  {
    firstName: "Bob",
    lastName: "Belcher",
    gardenAddress: "Bellevue",
    email: "bob@test.com",
    password: "password",
    orders: [
      {
        // products: [products[0]._id, products[0]._id, products[1]._id],
      },
    ],
  }
]);

  console.log("User seeded");

  await Product.deleteMany();

  const products = await Product.insertMany([
    {
      name: "carrot",
      expirationDate: "12 days",
      description: "fresh organic multi colored carrots",
      image: "https://img.icons8.com/external-dreamcreateicons-outline-color-dreamcreateicons/452/external-carrot-autumn-season-dreamcreateicons-outline-color-dreamcreateicons.png",
      category: categories[0]._id,
      price: 2.99,
      quantity: 500,
      user: user[0]._id,
    },
    {
      name: "onion",
      expirationDate: "10 days",
      description: "Fresh Organic Red Onion",
      image: "../../client/src/images/redOnion.png",
      category: categories[0]._id,
      price: 1.99,
      quantity: 500,
      user: user[0]._id,
    },
    {
      name: "cabbage",
      expirationDate: "16 days",
      category: categories[0]._id,
      description: "fresh organic head of cabbage",
      image: "../../client/src/images/cabbage.png",
      price: 7.99,
      quantity: 20,
      user: user[1]._id,
    },
    {
      name: "basil",
      expirationDate: "20 days",
      category: categories[2]._id,
      description: "Bundles of fresh organic basil leaves",
      image: "../../client/src/images/basil.png",
      price: 3.99,
      quantity: 50,
      user: user[1]._id,
    },
    {
      name: "celery",
      expirationDate: "12 days",
      category: categories[0]._id,
      description: "bundles of fresh organic Celery",
      image: "../../client/src/images/celery.png",
      price: 14.99,
      quantity: 100,
      user: user[0]._id,
    },
    {
      name: "apple",
      expirationDate: "14 days",
      category: categories[1]._id,
      description: "Fresh Organic Honeycrisp Apples",
      image: "../../client/src/images/apple.png",
      price: 2.99,
      quantity: 30,
      user: user[0]._id,
    },
    {
      name: "strawberries",
      expirationDate: "20 days",
      category: categories[1]._id,
      description: "fresh organic box of strawberries",
      image: "../../client/src/images/strawberry.png",
      price: 2.99,
      quantity: 30,
      user: user[0]._id,
    },
    {
      name: "corn",
      expirationDate: "18 days",
      category: categories[0]._id,
      description: "fresh organic ears of golden corn",
      image: "../../client/src/images/corn.png",
      price: 1.99,
      quantity: 300,
      user: user[1]._id,
    },
    {
      name: "oranges",
      expirationDate: "10 days",
      category: categories[1]._id,
      description: "fresh organic Navel oranges",
      image: "../../client/src/images/orange.png",
      price: 1.99,
      quantity: 1000,
      user: user[1]._id,
    },
    {
      name: "potato",
      expirationDate: "14 days",
      category: categories[0]._id,
      description: "fresh organic russet potato",
      image: "../../client/src/images/potato.png",
      price: 1.99,
      quantity: 100,
      user: user[0]._id,
    },
    {
      name: "tomato",
      expirationDate: "4 days",
      category: categories[1]._id,
      description: "Fresh organic Heirloom tomato",
      image: "../../client/src/images/tomato.png",
      price: 2.99,
      quantity: 600,
      user: user[0]._id,
    },
    {
      name: "lettuce",
      expirationDate: "8 days",
      category: categories[0]._id,
      description: "fresh organic Green leaf lettuce",
      image: "../../client/src/images/lettuce.png",
      price: 2.99,
      quantity: 40,
      user: user[0]._id,
    },
    {
      name: "radish",
      expirationDate: "14 days",
      category: categories[0]._id,
      description: "fresh organic Radishes",
      image: "../../client/src/images/radish.png",
      price: 4.99,
      quantity: 200,
      user: user[0]._id,
    },
    {
      name: "beet",
      expirationDate: "20 days",
      category: categories[0]._id,
      description: "fresh organic red beets",
      image: "../../client/src/images/beet.png",
      price: 1.99,
      quantity: 240,
      user: user[0]._id,
    },
    {
      name: "garlic",
      expirationDate: "50 days",
      category: categories[0]._id,
      description: "fresh organic Garlic Cloves",
      image: "../../client/src/images/garlic.png",
      price: 3.99,
      quantity: 450,
      user: user[2]._id,
    },
    {
      name: "leek",
      expirationDate: "12 days",
      category: categories[0]._id,
      description: "fresh organic water leeks",
      image: "../../client/src/images/leek.png",
      price: 4.99,
      quantity: 150,
      user: user[2]._id,
    },
    {
      name: "broccoli",
      expirationDate: "13 days",
      category: categories[0]._id,
      description: "fresh organic Head of broccoli",
      image: "../../client/src/images/broccoli.png",
      price: 4.99,
      quantity: 80,
      user: user[2]._id,
    },
    {
      name: "peas",
      expirationDate: "15 days",
      category: categories[0]._id,
      description: "fresh organic Snap Peas",
      image: "../../client/src/images/peas.png",
      price: 1.99,
      quantity: 640,
      user: user[2]._id,
    },
    {
      name: "blueberries",
      expirationDate: "6 days",
      category: categories[1]._id,
      description: "Fresh Organic Blueberries",
      image: "../../client/src/images/blueberry.png",
      price: 5.99,
      quantity: 130,
      user: user[2]._id,
    },
    {
      name: "cherries",
      expirationDate: "13 days",
      category: categories[1]._id,
      description: "Fresh Organic cherries",
      image: "../../client/src/images/cherry.png",
      price: 3.99,
      quantity: 240,
      user: user[2]._id,
    },
    {
      name: "watermelon",
      expirationDate: "20 days",
      category: categories[1]._id,
      description: "Fresh Organic Watermelon",
      image: "../../client/src/images/watermelon.png",
      price: 6.99,
      quantity: 360,
      user: user[2]._id,
    },
    {
      name: "raspberries",
      expirationDate: "9 days",
      category: categories[1]._id,
      description: "Fresh Organic Raspberries",
      image: "../../client/src/images/raspberry.png",
      price: 8.99,
      quantity: 170,
      user: user[2]._id,
    },
    {
      name: "cucumber",
      expirationDate: "14 days",
      category: categories[1]._id,
      description: "Fresh Organic cucumber",
      image: "../../client/src/images/cucumber.png",
      price: 4.99,
      quantity: 450,
      user: user[2]._id,
    },
    {
      name: "peppers",
      expirationDate: "11 days",
      category: categories[1]._id,
      description: "Fresh Organic Red Peppers",
      image: "../../client/src/images/pepper.png",
      price: 4.99,
      quantity: 560,
      user: user[2]._id,
    },
    {
      name: "grapes",
      expirationDate: "17 days",
      category: categories[1]._id,
      description: "Fresh Organic Concord Grapes",
      image: "../../client/src/images/grape.png",
      price: 5.99,
      quantity: 150,
      user: user[1]._id,
    },
    {
      name: "eggplant",
      expirationDate: "20 days",
      category: categories[1]._id,
      description: "Fresh Organic eggplant",
      image: "../../client/src/images/eggplant.png",
      price: 3.99,
      quantity: 30,
      user: user[1]._id,
    },
    {
      name: "bananas",
      expirationDate: "7 days",
      category: categories[1]._id,
      description: "Fresh Organic Ripe bananas",
      image: "../../client/src/images/banana.png",
      price: 4.99,
      quantity: 300,
      user: user[1]._id,
    },
    {
      name: "avacado",
      expirationDate: "9 days",
      category: categories[1]._id,
      description: "Fresh Organic Avacados",
      image: "../../client/src/images/avacado.png",
      price: 6.99,
      quantity: 190,
      user: user[1]._id,
    },
    {
      name: "asparagus",
      expirationDate: "13 days",
      category: categories[0]._id,
      description: "fresh organic asparagus",
      image: "../../client/src/images/asparagus.png",
      price: 5.99,
      quantity: 270,
      user: user[0]._id,
    },
    {
      name: "mint",
      expirationDate: "6 days",
      category: categories[2]._id,
      description: "Bundles of fresh organic mint leaves",
      image: "../../client/src/images/mint.png",
      price: 4.99,
      quantity: 140,
      user: user[1]._id,
    },
    {
      name: "rosemary",
      expirationDate: "7 days",
      category: categories[2]._id,
      description: "Bundles of fresh organic rosemary twigs",
      image: "../../client/src/images/rosemary.png",
      price: 5.99,
      quantity: 450,
      user: user[1]._id,
    },
    {
      name: "lavender",
      expirationDate: "9 days",
      category: categories[2]._id,
      description: "Bundles of fresh organic lavender twigs",
      image: "../../client/src/images/lavender.png",
      price: 5.99,
      quantity: 50,
      user: user[1]._id,
    },
    {
      name: "thyme",
      expirationDate: "13 days",
      category: categories[2]._id,
      description: "Bundles of fresh organic thyme",
      image: "../../client/src/images/thyme.png",
      price: 5.99,
      quantity: 60,
      user: user[1]._id,
    },
    {
      name: "bay leafs",
      expirationDate: "7 days",
      category: categories[2]._id,
      description: "Bundles of fresh organic bay leaves",
      image: "../../client/src/images/bayLeaf.png",
      price: 3.99,
      quantity: 50,
      user: user[1]._id,
    },
  ]);

  console.log("products seeded");

  await User.findOneAndUpdate(user[0]._id, {
    "$addToSet":{"orders": [products[0]._id, products[0]._id, products[1]._id]},
    },)
  await User.findOneAndUpdate(user[1]._id, {
    "$addToSet":{"orders": [products[0]._id, products[0]._id, products[1]._id]},
    },)
  await User.findOneAndUpdate(user[2]._id, {
    "$addToSet":{"orders": [products[0]._id, products[0]._id, products[1]._id]},
    },)
    

  process.exit();
});
