const db = require("../config/connection");
const { User, Product, Category, Order } = require("../models");

db.once("open", async () => {
  await Category.deleteMany();

  const categories = await Category.insertMany([
    { name: "vegetables" },
    { name: "fruits" },
    { name: "herbs" },
  ]);

  console.log("categories seeded");

  await User.deleteMany();



  const user = await User.insertMany([
    {
    firstName: "Peter",
    lastName: "Griffin",
    gardenAddress: "Seattle",
    email: "peter@test.com",
    password: "password",
    orders: [
      {
        // products: [products[0]._id, products[0]._id, products[1]._id],
      },
    ],
  },
  {
    firstName: "Chris",
    lastName: "Griffin",
    gardenAddress: "Seattle1",
    email: "chris@test.com",
    password: "password",
    orders: [
      {
        // products: [products[0]._id, products[0]._id, products[1]._id],
      },
    ],
  },
  {
    firstName: "Bob",
    lastName: "Belcher",
    gardenAddress: "Bellevue",
    email: "bob@test.com",
    password: "password",
    orders: [
      {
        // products: [products[0]._id, products[0]._id, products[1]._id],
      },
    ],
  }
]);

  console.log("User seeded");

  await Product.deleteMany();

  const products = await Product.insertMany([
    {
      name: "carrot",
      expirationDate: "12 days",
      description: "fresh organic multi colored carrots",
      image: "https://img.icons8.com/external-dreamcreateicons-outline-color-dreamcreateicons/452/external-carrot-autumn-season-dreamcreateicons-outline-color-dreamcreateicons.png",
      category: categories[0]._id,
      price: 2.99,
      quantity: 500,
      user: user[0]._id,
    },
    {
      name: "onion",
      expirationDate: "10 days",
      description: "Fresh Organic Yellow Onion",
      image: "https://img.icons8.com/emoji/344/onion-emoji.png",
      category: categories[0]._id,
      price: 1.99,
      quantity: 500,
      user: user[0]._id,
    },
    {
      name: "cabbage",
      expirationDate: "16 days",
      category: categories[0]._id,
      description: "fresh organic head of cabbage",
      image: "https://img.icons8.com/external-ddara-lineal-color-ddara/344/external-cabbage-vegetables-ddara-lineal-color-ddara.png",
      price: 7.99,
      quantity: 20,
      user: user[1]._id,
    },
    {
      name: "basil",
      expirationDate: "20 days",
      category: categories[2]._id,
      description: "Bundles of fresh organic basil leaves",
      image: "https://img.icons8.com/color/452/basil.png",
      price: 3.99,
      quantity: 50,
      user: user[1]._id,
    },
    {
      name: "celery",
      expirationDate: "12 days",
      category: categories[0]._id,
      description: "bundles of fresh organic Celery",
      image: "https://img.icons8.com/color/344/celery.png",
      price: 14.99,
      quantity: 100,
      user: user[0]._id,
    },
    {
      name: "apple",
      expirationDate: "14 days",
      category: categories[1]._id,
      description: "Fresh Organic Honeycrisp Apples",
      image: "https://img.icons8.com/doodle/344/apple.png",
      price: 2.99,
      quantity: 30,
      user: user[0]._id,
    },
    {
      name: "strawberries",
      expirationDate: "20 days",
      category: categories[1]._id,
      description: "fresh organic box of strawberries",
      image: "https://img.icons8.com/doodle/452/strawberry-2.png",
      price: 2.99,
      quantity: 30,
      user: user[0]._id,
    },
    {
      name: "corn",
      expirationDate: "18 days",
      category: categories[0]._id,
      description: "fresh organic ears of golden corn",
      image: "https://img.icons8.com/emoji/452/ear-of-corn.png",
      price: 1.99,
      quantity: 300,
      user: user[1]._id,
    },
    {
      name: "oranges",
      expirationDate: "10 days",
      category: categories[1]._id,
      description: "fresh organic Navel oranges",
      image: "https://img.icons8.com/external-justicon-lineal-color-justicon/344/external-orange-korea-justicon-lineal-color-justicon.png",
      price: 1.99,
      quantity: 1000,
      user: user[1]._id,
    },
    {
      name: "potato",
      expirationDate: "14 days",
      category: categories[0]._id,
      description: "fresh organic russet potato",
      image: "https://img.icons8.com/emoji/344/potato-emoji.png",
      price: 1.99,
      quantity: 100,
      user: user[0]._id,
    },
    {
      name: "tomato",
      expirationDate: "4 days",
      category: categories[1]._id,
      description: "Fresh organic Heirloom tomato",
      image: "https://img.icons8.com/external-icongeek26-linear-colour-icongeek26/344/external-tomato-vegan-icongeek26-linear-colour-icongeek26.png",
      price: 2.99,
      quantity: 600,
      user: user[0]._id,
    },
    {
      name: "lettuce",
      expirationDate: "8 days",
      category: categories[0]._id,
      description: "fresh organic Green leaf lettuce",
      image: "https://img.icons8.com/external-ddara-lineal-color-ddara/344/external-lettuce-vegetables-ddara-lineal-color-ddara-1.png",
      price: 2.99,
      quantity: 40,
      user: user[0]._id,
    },
    {
      name: "radish",
      expirationDate: "14 days",
      category: categories[0]._id,
      description: "fresh organic Radishes",
      image: "https://img.icons8.com/external-vitaliy-gorbachev-lineal-color-vitaly-gorbachev/452/external-radish-vegetable-vitaliy-gorbachev-lineal-color-vitaly-gorbachev.png",
      price: 4.99,
      quantity: 200,
      user: user[0]._id,
    },
    {
      name: "beet",
      expirationDate: "20 days",
      category: categories[0]._id,
      description: "fresh organic red beets",
      image: "https://img.icons8.com/color/452/beet.png",
      price: 1.99,
      quantity: 240,
      user: user[0]._id,
    },
    {
      name: "garlic",
      expirationDate: "50 days",
      category: categories[0]._id,
      description: "fresh organic Garlic Cloves",
      image: "https://img.icons8.com/external-icongeek26-linear-colour-icongeek26/344/external-garlic-vegan-icongeek26-linear-colour-icongeek26.png",
      price: 3.99,
      quantity: 450,
      user: user[2]._id,
    },
    {
      name: "leek",
      expirationDate: "12 days",
      category: categories[0]._id,
      description: "fresh organic water leeks",
      image: "https://img.icons8.com/external-flat-land-kalash/344/external-food-food-flat-land-kalash-40.png",
      price: 4.99,
      quantity: 150,
      user: user[2]._id,
    },
    {
      name: "broccoli",
      expirationDate: "13 days",
      category: categories[0]._id,
      description: "fresh organic Head of broccoli",
      image: "https://img.icons8.com/external-ddara-lineal-color-ddara/452/external-broccoli-vegetables-ddara-lineal-color-ddara.png",
      price: 4.99,
      quantity: 80,
      user: user[2]._id,
    },
    {
      name: "peas",
      expirationDate: "15 days",
      category: categories[0]._id,
      description: "fresh organic Snap Peas",
      image: "https://img.icons8.com/plasticine/344/peas.png",
      price: 1.99,
      quantity: 640,
      user: user[2]._id,
    },
    {
      name: "blueberries",
      expirationDate: "6 days",
      category: categories[1]._id,
      description: "Fresh Organic Blueberries",
      image: "https://img.icons8.com/external-icongeek26-linear-colour-icongeek26/344/external-blueberry-vegan-icongeek26-linear-colour-icongeek26.png",
      price: 5.99,
      quantity: 130,
      user: user[2]._id,
    },
    {
      name: "cherries",
      expirationDate: "13 days",
      category: categories[1]._id,
      description: "Fresh Organic cherries",
      image: "https://img.icons8.com/external-justicon-lineal-color-justicon/452/external-cherry-gambling-justicon-lineal-color-justicon.png",
      price: 3.99,
      quantity: 240,
      user: user[2]._id,
    },
    {
      name: "watermelon",
      expirationDate: "20 days",
      category: categories[1]._id,
      description: "Fresh Organic Watermelon",
      image: "https://img.icons8.com/external-filled-line-andi-nur-abdillah/344/external-watermelon-vegetable-and-fruit-filled-line-filled-line-andi-nur-abdillah.png",
      price: 6.99,
      quantity: 360,
      user: user[2]._id,
    },
    {
      name: "raspberries",
      expirationDate: "9 days",
      category: categories[1]._id,
      description: "Fresh Organic Raspberries",
      image: "https://img.icons8.com/doodle/344/raspberry--v1.png",
      price: 8.99,
      quantity: 170,
      user: user[2]._id,
    },
    {
      name: "cucumber",
      expirationDate: "14 days",
      category: categories[1]._id,
      description: "Fresh Organic cucumber",
      image: "https://img.icons8.com/external-filled-line-andi-nur-abdillah/344/external-cucumber-vegetable-and-fruit-filled-line-filled-line-andi-nur-abdillah.png",
      price: 4.99,
      quantity: 450,
      user: user[2]._id,
    },
    {
      name: "peppers",
      expirationDate: "11 days",
      category: categories[1]._id,
      description: "Fresh Organic Red Peppers",
      image: "https://img.icons8.com/doodle/344/paprika--v1.png",
      price: 4.99,
      quantity: 560,
      user: user[2]._id,
    },
    {
      name: "grapes",
      expirationDate: "17 days",
      category: categories[1]._id,
      description: "Fresh Organic Concord Grapes",
      image: "https://img.icons8.com/external-dreamcreateicons-outline-color-dreamcreateicons/344/external-grape-autumn-season-dreamcreateicons-outline-color-dreamcreateicons.png",
      price: 5.99,
      quantity: 150,
      user: user[1]._id,
    },
    {
      name: "eggplant",
      expirationDate: "20 days",
      category: categories[1]._id,
      description: "Fresh Organic eggplant",
      image: "https://img.icons8.com/external-ddara-lineal-color-ddara/344/external-eggplant-vegetables-ddara-lineal-color-ddara.png",
      price: 3.99,
      quantity: 30,
      user: user[1]._id,
    },
    {
      name: "bananas",
      expirationDate: "7 days",
      category: categories[1]._id,
      description: "Fresh Organic Ripe bananas",
      image: "https://img.icons8.com/plasticine/344/banana.png",
      price: 4.99,
      quantity: 300,
      user: user[1]._id,
    },
    {
      name: "avacado",
      expirationDate: "9 days",
      category: categories[1]._id,
      description: "Fresh Organic Avacados",
      image: "https://img.icons8.com/external-justicon-lineal-color-justicon/344/external-avocado-healthy-food-and-vegan-justicon-lineal-color-justicon.png",
      price: 6.99,
      quantity: 190,
      user: user[1]._id,
    },
    {
      name: "asparagus",
      expirationDate: "13 days",
      category: categories[0]._id,
      description: "fresh organic asparagus",
      image: "https://img.icons8.com/external-icongeek26-linear-colour-icongeek26/344/external-asparagus-vegetables-icongeek26-linear-colour-icongeek26.png",
      price: 5.99,
      quantity: 270,
      user: user[0]._id,
    },
    {
      name: "mint",
      expirationDate: "6 days",
      category: categories[2]._id,
      description: "Bundles of fresh organic mint leaves",
      image: "https://img.icons8.com/color/344/mint.png",
      price: 4.99,
      quantity: 140,
      user: user[1]._id,
    },
    {
      name: "rosemary",
      expirationDate: "7 days",
      category: categories[2]._id,
      description: "Bundles of fresh organic rosemary twigs",
      image: "https://img.icons8.com/external-ddara-lineal-color-ddara/344/external-rosemary-natural-scent-ddara-lineal-color-ddara.png",
      price: 5.99,
      quantity: 450,
      user: user[1]._id,
    },
    {
      name: "lavender",
      expirationDate: "9 days",
      category: categories[2]._id,
      description: "Bundles of fresh organic lavender twigs",
      image: "https://img.icons8.com/external-icongeek26-linear-colour-icongeek26/452/external-Lavender-france-icongeek26-linear-colour-icongeek26.png",
      price: 5.99,
      quantity: 50,
      user: user[1]._id,
    },
    {
      name: "thyme",
      expirationDate: "13 days",
      category: categories[2]._id,
      description: "Bundles of fresh organic thyme",
      image: "https://img.icons8.com/plasticine/344/thyme.png",
      price: 5.99,
      quantity: 60,
      user: user[1]._id,
    },
    {
      name: "bay leafs",
      expirationDate: "7 days",
      category: categories[2]._id,
      description: "Bundles of fresh organic bay leaves",
      image: "https://img.icons8.com/color/344/bay-leaf.png",
      price: 3.99,
      quantity: 50,
      user: user[1]._id,
    },
  ]);

  console.log("products seeded");

  await User.findOneAndUpdate(user[0]._id, {
    "$addToSet":{"orders": [products[0]._id, products[0]._id, products[1]._id]},
    },)
  await User.findOneAndUpdate(user[1]._id, {
    "$addToSet":{"orders": [products[0]._id, products[0]._id, products[1]._id]},
    },)
  await User.findOneAndUpdate(user[2]._id, {
    "$addToSet":{"orders": [products[0]._id, products[0]._id, products[1]._id]},
    },)
    

  process.exit();
});
