export const ADD_TO_CHART = "ADD_TO_CHART";
export const ADD_MULTIPLE_TO_CHART = "ADD_MULTIPLE_TO_CHART";
export const UPDATE_CHART_QUANTITY = "UPDATE_CHART_QUANTITY";
export const REMOVE_FROM_CHART = "REMOVE_FROM_CHART";
export const CLEAR_CART = "CLEAR_CART";
export const TOGGLE_CART = "TOGGLE_CART";
